name: Build symbol maps

on: [push]

permissions:
  contents: write

jobs:
    build_maps:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - uses: actions/checkout@master
              with:
                repository: RoadrunnerWMC/wii-code-tools
                path: wii-code-tools

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                
            - name: Make symbol maps
              run: python build.py
                
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: NSMBW Symbol Maps
                path: ./maps

            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: 'v1.0'
                release_name: 'Autogenerated symbol maps'
                draft: false
                prerelease: false
