name: Build symbol maps

on: [push]

permissions:
  contents: write

jobs:
    build_maps:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - uses: actions/checkout@master
              with:
                repository: RoadrunnerWMC/wii-code-tools
                path: wii-code-tools

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                
            - name: Make symbol maps
              run: python build.py

            - name: Get date and time
              id: date
              run: echo "::set-output name=datetime::$(date +'%Y-%m-%d_%H-%M-%S')"

            - name: Create zip artifact
              run: zip -r -j NSMBW_Symbol_Maps_${{ steps.date.outputs.datetime }}.zip maps

            - name: Remove old release artifacts
              uses: mknejp/delete-release-assets@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                tag: 'v1.0'
                assets: 'NSMBW_Symbol_Maps_*.zip'

            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                allowUpdates: true
                tag: 'v1.0'
                name: 'Autogenerated symbol maps'
                artifacts: ./NSMBW_Symbol_Maps_${{ steps.date.outputs.datetime }}.zip
