name: Build symbol maps

on: [push]

permissions:
    contents: read

jobs:
    build_maps:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - uses: actions/checkout@master
              with:
                repository: RoadrunnerWMC/wii-code-tools
                path: wii-code-tools

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                
            - name: Make symbol maps
              run: python build.py
                
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: NSMBW Symbol Maps
                path: ./maps
